config/routes.rb
Rails.application.routes.draw do

  resources :notes
  resources :tasks

  resources :projects, shallow: true do
    resources :tasks do
      member do
        put :pause, :stop
      end
    end
    resources :steps do
      member do
        put :order_up
      end
    end
    resources :entities
  end

  get "newchecklist" => "projects#newchecklist"
  get "newprocess" => "projects#newprocess"

  devise_for :accounts
  
  resources :accounts, :only => [:index, :new, :create, :destroy]

  devise_for :users
  resources :users, only: [:index]
  root 'pages#home'
  get "about" => "pages#about"
  get "settings" => "pages#settings"
  get "dashboard" => "pages#dashboard"
  get "faq" => "pages#faq"

end

app/models/entity.rb
class Entity < ActiveRecord::Base
	belongs_to :project

	validates :name, presence: true

	default_scope { order('step_id','updated_at') }

	def to_param
    	"#{id} #{name}".parameterize
  	end

	#include PublicActivity::Model
  	#tracked owner: Proc.new{ |controller, model| controller.current_user }
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @project = Project.find(params[:project_id])
    @entity = @project.entities.build
  end

  # GET /entities/1/edit
  def edit
    @users = User.where('account_num = ?',current_user.account_num)
    @projects = Project.where("creator IN (?)", @users.pluck(:email))
  end

  # POST /entities
  # POST /entities.json
  def create
    @users = User.where('account_num = ?',current_user.account_num)
    @project = Project.find(params[:project_id])
    @entity = @project.entities.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @project, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    @users = User.where('account_num = ?',current_user.account_num)
    @project = Project.find(@entity.project_id)
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @project, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @project = Project.find(@entity.project_id)
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to @project, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params.require(:entity).permit(:id, :name, :notes, :contact, :step_id, :project_id, :created_at, :updated_at)
    end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.erb
<%= simple_form_for([@project, @entity]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :autofocus => true %>
  </div>
  <br>

  <div class="form-inputs">
    <%= f.input :notes %>
  </div>
  <br>

  <div class="form-inputs">
    <%= f.input :contact %>
  </div>
  <br>

  <div class="form-inputs">
    <%= f.input :step_id %>
  </div>
  <br>
  

  <div class="form-actions">
    <button type="submit" class="btn btn-success">
        <i class="fa fa-floppy-o fa-lg"></i>  Save
    </button>
  </div>
<% end %>

app/views/entities/edit.html.erb
<ol class="breadcrumb">
	<li><%= link_to 'All Projects', projects_path %></li>
	<li><%= link_to Project.find(@entity.project_id).title, Project.find(@entity.project_id) %></li>
	<li class="active"><u>Edit Entity</u></li>
</ol>

<div class="well">
	<%= render 'form' %>
	<br>
	<%= link_to @entity, method: :delete, data: { confirm: 'Delete entity? This action cannot be undone' }, class: "btn btn-danger" do %>
	  <i class="fa fa-trash-o fa-lg"></i>
	  Delete Entity
	<% end %>
</div>

<ul class="pager">
	<li class="previous"><%= link_to 'Back', Project.find(@entity.project_id) %></li>
</ul>

app/views/entities/index.html.erb
<h1>Listing entities</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= link_to 'Show', entity %></td>
        <td><%= link_to 'Edit', edit_entity_path(entity) %></td>
        <td><%= link_to 'Destroy', entity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entity', new_entity_path %>

app/views/entities/new.html.erb
<ol class="breadcrumb">
	<li><%= link_to 'All Projects', projects_path %></li>
	<li><%= link_to Project.find(@entity.project_id).title, Project.find(@entity.project_id) %></li>
	<li class="active"><u>New Entity</u></li>
</ol>

<div class="well">
	<%= render 'form' %>
</div>

<ul class="pager">
	<li class="previous"><%= link_to 'Back', Project.find(@entity.project_id) %></li>
</ul>

app/views/entities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_entity_path(@entity) %> |
<%#= link_to 'Back', entities_path %>