config/routes.rb
Rails.application.routes.draw do

  resources :notes
  resources :tasks

  resources :projects, shallow: true do
    resources :tasks do
      member do
        put :pause, :stop
      end
    end
    resources :steps do
      member do
        put :order_up
      end
    end
    resources :entities
  end

  get "newchecklist" => "projects#newchecklist"
  get "newprocess" => "projects#newprocess"

  devise_for :accounts
  
  resources :accounts, :only => [:index, :new, :create, :destroy]

  devise_for :users
  resources :users, only: [:index]
  root 'pages#home'
  get "about" => "pages#about"
  get "settings" => "pages#settings"
  get "dashboard" => "pages#dashboard"
  get "faq" => "pages#faq"

end

app/views/pages/OLDdashboard.html.erb
<div class="jumbotron">
	<h2>Dashboard</h2>
</div>
<% Groupdate.time_zone = "Pacific Time (US & Canada)" %>

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Total Projects
		    <span class="badge badge-dark">
		    	<%= @projects.count %>
		    </span>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse">
      <div class="panel-body">
      	<div class="col-md-6">
        	<%= pie_chart @projects.group(:category).count, library: {title: 'Project Breakdown by Category', pieHole: 0.4} %>
        </div>
        <div class="col-md-6">
        	<%= pie_chart @projects.group(:creator).count, library: {title: 'Project Breakdown by Creator', pieHole: 0.4} %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Total Tasks
		    <span class="badge badge-dark">
		    	<%= @tasks.count %>
		    </span>
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
      	<div class="col-md-3">
        	<%= pie_chart @tasks.group(:done).count, library: {title: 'Task Breakdown by Not Done/Done', pieHole: 0.4} %>
        </div>
      	<div class="col-md-3">
        	<%= pie_chart @tasks.group(:project_id).count, library: {title: 'Task Breakdown by Project', pieHole: 0.4} %>
        </div>
        <div class="col-md-3">
        	<%= pie_chart @tasks.group(:creator).count, library: {title: 'Task Breakdown by Creator', pieHole: 0.4} %>
    	</div>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          Total Steps
		    <span class="badge badge-dark">
		    	<%= @steps.count %>
		    </span>
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        <div class="col-md-3">
        	<%= pie_chart @steps.group(:project_id).count, library: {title: 'Step Breakdown by Project', pieHole: 0.4} %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          Total Entities
		    <span class="badge badge-dark">
		    	<%= @entities.count %>
		    </span>
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
      <div class="panel-body">
        <%= pie_chart @entities.group(:project_id).count, library: {title: 'Entity Breakdown by Project', pieHole: 0.4} %>
      </div>
    </div>
  </div>
</div>

app/views/pages/OLDhome.html.erb
<p>
	<% if user_signed_in? %>
		<div class="container">
			<div class="jumbotron">
				<h2>
					Welcome,
					<% if current_user.name == nil || current_user.name == "" %>
						<%= current_user.email %>!
					<% else %>
						<%= current_user.name %>!
					<% end %>
				</h2>
			</div>
			<div class="well">
				<% @awaiting = [] %>
				<% @myassigned = [] %>
				<% @myopenhigh = [] %>
				<% @myopenpastdue = [] %>
				<% @myopentoday = [] %>
				<% @myopenweek = [] %>
				<% @projects.each do |project| %>
		        	<% @awaiting = @awaiting + project.tasks.where('creator != ?', current_user.email).where('assignee = ?', current_user.email).where('done = ?', false).where('accepted = ?', nil) %>
		        	<% @myassigned = @myassigned + project.tasks.where('creator != ?', current_user.email).where('assignee = ?', current_user.email).where('done = ?', false).where('accepted = ?', true) %>
		        	<% @myopenhigh = @myopenhigh + project.tasks.where('creator = ?', current_user.email).where('done = ?', false).where('assignee = ? OR assignee = ?',nil,"").where('importance = ?','priority').where('priority = ?','high') %>
		        	<% @myopenpastdue = @myopenpastdue + project.tasks.where('creator = ?', current_user.email).where('done = ?', false).where('assignee = ? OR assignee = ?',nil,"").where('importance = ?','due').where('duedate < ?',Date.today) %>
		        	<% @myopentoday = @myopentoday + project.tasks.where('creator = ?', current_user.email).where('done = ?', false).where('assignee = ? OR assignee = ?',nil,"").where('importance = ?','due').where('duedate = ?',Date.today) %>
		        	<% @myopenweek = @myopenweek + project.tasks.where('creator = ?', current_user.email).where('done = ?', false).where('assignee = ? OR assignee = ?',nil,"").where('importance = ?','due').where('duedate < ?',Date.today).where('duedate > ?', Date.today.end_of_week) %>
		      	<% end %>
		      	<% if @awaiting.count > 0 %>
		      		<%= link_to tasks_path(anchor: "awaiting") do %>
		      			You have <%= @awaiting.count %> items awaiting your approval.
	      			<% end %>
	      			<% @awaiting.each do |task| %>
	      				<%= task.description %><br>
	      			<% end %>
      			<% end %>
      			<% if @myassigned.count > 0 %>
      				<%= link_to tasks_path(anchor: "myassigned") do %>
      					You have <%= @myassigned.count %> items assigned to you.
      				<% end %>
      				<% @myassigned.each do |task| %>
	      				<%= task.description %><br>
	      			<% end %>
      			<% end %>
      			
  				
				<% if @myopenhigh.count > 0 %>
					You have <%= @myopenhigh.count %> high priority item(s).
					<br>
				<% end %>
				<% @myopenhigh.each do |task| %>
	  				<%= link_to task.description, edit_task_path(task) %><br>
	  			<% end %>
				<% if @myopenpastdue.count > 0 %>
					You have <%= @myopenpastdue.count %> item(s) past due.
					<br>
				<% end %>
				<% @myopenpastdue.each do |task| %>
	  				<%= link_to task.description, edit_task_path(task) %><br>
	  			<% end %>
				<% if @myopentoday.count > 0 %>
					You have <%= @myopentoday.count %> item(s) due today.
					<br>
				<% end %>
				<% @myopentoday.each do |task| %>
  					<%= link_to task.description, edit_task_path(task) %><br>
	  			<% end %>
				<% if @myopenweek.count > 0 %>
					You have <%= @myopenweek.count %> item(s) due this week.
				<% end %>
				<% @myopenweek.each do |task| %>
	  				<%= link_to task.description, edit_task_path(task) %><br>
	  			<% end %>
			</div>
		</div>
	<% elsif account_signed_in? %>
		<div class="jumbotron">
			Welcome <strong><%= current_account.email %></strong>
		</div>
	<% else %>
		<div class="home-1 container-fluid">
			
			<%#= image_tag(image_path("catalist-white-new-large.png"), size: "180x40",) %>
			<br>
			<h1>Get Focused & Stay Productive</h1>
			<h4>
				Empower your team with a simple solution for their entire workload
			</h4>
			<br>
			<br>
			<!-- Text ideas
			Manage everything you need to do, simply & securely.

			Your company's task list simplified and consolidated.
			Know what you need to do, now.

			Get your company into the Productive Age
			<div class="opacity-box">

				<!-- Begin MailChimp Signup Form -->
				<!--
				<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
			-->

			<style type="text/css">
				#mc_embed_signup{background:transparent; clear:left; font:14px Helvetica,Arial,sans-serif; }
				/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
				   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
			</style>
				
					
					
			<div class="mc_embed_signup">

				<form action="//sugam.us8.list-manage.com/subscribe/post?u=166a17340815f01e4ce780c4b&amp;id=93fcb9619c" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
					<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
					<span style="position: absolute; left: -5000px;"><input type="text" name="b_166a17340815f01e4ce780c4b_93fcb9619c" tabindex="-1" value=""></span>
					<span class="mailchimp-form">
						<input type="email" value="" name="EMAIL" class="email textbox-email" id="mce-EMAIL" placeholder="email address" required autofocus="on">
				    	<input type="submit" value="Invite me!" name="subscribe" id="mc-embedded-subscribe" class="btn btn-success btn-email">
				    </span>
				</form>
				<!--End mc_embed_signup-->
				<br>
				<br>
				<br>
				<i>Get your company early access to the beta</i>    
				<br>
			</div>
		</div>

		<!--
		<div class="home-2">
			<span>Has your company already signed up & you have a username?</span>
			<span><%#= link_to "Sign in", new_user_session_path, class: "btn btn-default btn-lg" %></span>
		</div>
		-->
		<!--
		<div class="container-fluid home-1">
			Get productive <i>now</i>:
			<%#= form_for :beta, :url => {:action => :create} do |f| %>
  				
  				<div class="field">
      				<%#= f.label :email %>
      				<%#= f.text_field :email, :autofocus => true %>
    			</div>
    			
			    <button type="submit" class="btn btn-success">
			        <i class="fa fa-floppy-o fa-lg"></i> Submit
			    </button>
			  	
		  	<%# end %>
		</div>
	-->
		<div class="home-2 container-fluid">
			<div class="col-md-4 box">
				<h2 class="center-align">
					Lean Mean, Task Machine
				</h2>
				<div class="home-2-numbered">
					Catalist is ready for anything you got. It handles checklists, pipelines, and even basic notes. However you track it, rest easy knowing Catalist can do it more simply AND all in one place.
				</div>
				<h1 class="center-align">
					<i class="fa fa-cogs fa-lg"></i>
				</h1>
			</div>
			<div class="col-md-4 box">
				<h2 class="center-align">
					For the Whole Team
				</h2>
				Control access to content and quickly delegate work to anyone on your team. Transparency & accountability creates empowered employees.
				<h1 class="center-align">
					<i class="fa fa-users fa-lg"></i>
				</h1>
			</div>
			<div class="col-md-4 box">
				<h2 class="center-align">
					Wherever Work Takes You
				</h2>
				Catalist works on every Internet-connected device. Your laptop, smartphone, and tablet are all compatible so you can even Catalist at home. Every feature on every device in every location.
				<h1 class="center-align">
					<i class="fa fa-road fa-lg"></i>
				</h1>
			</div>
		</div>
	
		<div class="home-3">
			<!-- Feature #1 -->
			<div class="features container-fluid">
				<div class="center-align">
					<span class="numbers">1. Doing</span>
					<h2>More than just done & not done</h2>
				</div>
				<div class="col-md-6 center-align">
					<h4>Stay focused by specifying which task(s) you're currently working on. Forget being scatter-brained since you now know exactly what you are doing and where you left off. Best of all, you can let your supervisor and peers know what's the current task.
					</h4>
				</div>
				<div class="col-md-6 center-align outlined">
					<h3>
						<i class="fa fa-circle-o fa-warning"></i> Task To Do
					</h3>	
					<h2>
						<i class="fa fa-circle-o-notch fa-spin fa-info"></i> Task In Progress
					</h2>	
					<h3>
						<i class="fa fa-circle-o fa-success"></i> Task Complete
					</h3>
				</div>
			</div>
			<div class="divider"><br></div>
			<!-- Feature #2 -->
			<div class="features container-fluid">
				<div class="center-align">
					<span class="numbers">2. Tracking</span>
					<h2>Know how long you've spent</h2>
				</div>
				<div class="col-md-6 center-align">
					<h4>
						When you have an expectation of how long a task may take, it quickly becomes clear if you've spent too long. Catalist elegantly integrates time tracking for every task that comes up. No more thinking "Where did all the time go?!?"
					</h4>
				</div>
				<div class="col-md-6 center-align outlined">
					<h3>
						<i class="fa fa-play"></i> Start Tracking |
						<i class="fa fa-pause"></i> Pause Tracking
						<br>
						<i class="fa fa-refresh"></i> Reset Start Time |
						<i class="fa fa-stop"></i> Stop Tracking
					</h3>
				</div>
			</div>
			<div class="divider"><br></div>
			<!-- Feature #3 -->
			<div class="features container-fluid">
				<div class="center-align">
					<span class="numbers">3. Strategizing</span>
					<h2>Tackle the project that's most at risk</h2>
				</div>
				<div class="col-md-6 center-align">
					<h4>
						With more and more things to do, it's getting harder to know where to spend your time. By quickly seeing a project's status, you can rest easy knowing your time is well spent.
					</h4>
				</div>
				<div class="col-md-6 center-align outlined">
					<div class="panel panel-info">
				        <div class="panel-heading">
			          	  <i class="fa fa-check-circle-o fa-lg pull-right fa-panel" style="color:#fff"></i>
				          Top Secret Project  
				        </div>
				        <table class="table table-condensed">
				          <tr>
				            <td align="center">
								<input type="text" 
								value="3" data-max="10" 
                    			class="dial1" data-width="100" data-height="85" data-angleArc="250" data-angleOffset="-125" data-readOnly=true data-fgColor="#f0ad4e" data-bgColor="#5cb85c" data-thickness=".2" data-fontWeight="100" data-font="Helvetica">

			                  <script>
			                  $(function() {
			                      $(".dial1").knob({
			                      });
			                  });
			                  </script>
			              	</td>
			          	  </tr>
			      		</table>
			      	</div>
				</div>
			</div>
			<div class="divider"><br></div>
		</div>
	<% end %>
</p>

app/views/pages/about.html.erb
<div class="text-center">
	<%= image_tag(image_path("catalist-white-new-large.png")) %>
</div>
<br><br>
<div class="jumbotron">
	<h2>Catalist is the simple solution to your complex workplace</h2>
</div>

<div class="well">
	<h2>Beta Test</h2>
	<p>
		You and your company are using Catalist as part of a beta test. Although the product is completely free during this period, bugs, crashes, and occassional downtime may occur. However, the product will continue to get better everyday as we add new features, improve usability, and make it look better. We hope Catalist is useful and becomes an indispensible part of your workplace. Please communicate any issues you are experiencing or any other requests you may have via the Contact button above. Your data is secure and will be held confidentially. We hope you enjoy this beta test and would like to join us as regular customers when the time comes!
</div>
<div class="well">
	<h2>The Problem & Solution</h2>
	<p>	
		Let's see if the following sounds familiar: 
		<ul>
			<li>You are surrounded by computers but still have sheets of paper laying around</li>
			<li>You have something to ask your coworker but they happen to be busy</li>
			<li>You are constantly reminding others, and sometimes yourself, of important details</li>
		</ul>
	</p>

	<p>
		Enter Catalist. Catalist lets you create tasks, organize them, and assign them to your employees. Whether it's a basic to do list or a complex process with multiple steps, Catalist scales with you ensuring ease of use and powerful functionality. Catalist even has convenient features like a place for quick notes, due dates, priorities, and a simple workflow for accepting/rejecting assigned tasks.
	</p>
</div>

<div class="well">
	<h2>Catalist Basics</h2>
	<p>
		Here's the basic concepts on which Catalist is built. If you know these, you'll know Catalist.
		<ul>
			<li>Notes: Your bulletin board, post-its, and general announcements</li>
			<li>Checklist: To do lists for all those tasks that are either done or not done</li>
			<li>Process: Capture any and all your <i>pipelines</i></li>
			<ul>
				<li>Steps: The multiple parts that need to be finished in a specific order</li>
				<li>Entities: The items (e.g. candidates/clients/etc.) that go through all the steps</li>
			</ul>
		</ul>
	</p>
</div>

<div class="well">
	<h2>How To Use Catalist</h2>
	<p>
		First off, there's no wrong way to use Catalist. If it works for you and your team, then that's what Catalist is for. Try it out and see what happens.
	</p>
	<p>
		Here's a quick way to get started.
		<ul>
			<li>Assess your current workflow, processes, and software</li>
			<li>Identify things still being done on paper or just in conversations</li>
			<li>Consolidate things you need to do from other tools into Catalist (e.g. email, shared docs, shared drives, post-its, etc.)</li>
		</ul>
	</p>
	<p>
		Whether it's immediately obvious or not, Catalist provides solutions to all of the above. Feel free to reach out over email or phone so we can assess what works best for you and your business.
	</p>

app/views/pages/activity.html.erb
<div class="jumbotron">
	<h2>Activity</h2>
</div>

app/views/pages/dashboard.html.erb
<div class="jumbotron">
	<h2>Dashboard</h2>
</div>
<% Groupdate.time_zone = "Pacific Time (US & Canada)" %>

<!--<div id="myfirstchart" style="width: 200px; height: 200px;"></div>-->

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Total Projects
		    <span class="badge badge-dark">
		    	<%= @projects.count %>
		    </span>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse">
      <div class="panel-body">
      	<div class="col-md-6">
        	<%#= pie_chart @projects.group(:category).count, library: {title: 'Project Breakdown by Category', pieHole: 0.4} %>
        </div>
        <div class="col-md-6">
        	<%#= pie_chart @projects.group(:creator).count, library: {title: 'Project Breakdown by Creator', pieHole: 0.4} %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Total Tasks
		    <span class="badge badge-dark">
		    	<%= @tasks.count %>
		    </span>
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
      	<div class="col-md-3">
        	<%#= pie_chart @tasks.group(:done).count, library: {title: 'Task Breakdown by Not Done/Done', pieHole: 0.4} %>
        </div>
      	<div class="col-md-3">
        	<%#= pie_chart @tasks.group(:project_id).count, library: {title: 'Task Breakdown by Project', pieHole: 0.4} %>
        </div>
        <div class="col-md-3">
        	<%#= pie_chart @tasks.group(:creator).count, library: {title: 'Task Breakdown by Creator', pieHole: 0.4} %>
    	</div>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          Total Steps
		    <span class="badge badge-dark">
		    	<%= @steps.count %>
		    </span>
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        <div class="col-md-3">
        	<%#= pie_chart @steps.group(:project_id).count, library: {title: 'Step Breakdown by Project', pieHole: 0.4} %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          Total Entities
		    <span class="badge badge-dark">
		    	<%= @entities.count %>
		    </span>
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
      <div class="panel-body">
        <%#= pie_chart @entities.group(:project_id).count, library: {title: 'Entity Breakdown by Project', pieHole: 0.4} %>
      </div>
    </div>
  </div>
</div>

<!--
<script>
  new Morris.Line({
    // ID of the element in which to draw the chart.
    element: 'myfirstchart',
    // Chart data records -- each entry in this array corresponds to a point on
    // the chart.
    data: [
      { year: '2008', value: 20 },
      { year: '2009', value: 10 },
      { year: '2010', value: 5 },
      { year: '2011', value: 5 },
      { year: '2012', value: 20 }
    ],
    // The name of the data record attribute that contains x-values.
    xkey: 'year',
    // A list of names of data record attributes that contain y-values.
    ykeys: ['value'],
    // Labels for the ykeys -- will be displayed when you hover over the
    // chart.
    labels: ['Value'],
    resize: true,
    redraw: true
  });
</script>
-->

app/views/pages/faq.html.erb
<div class="jumbotron">
	<h2>Frequently Asked Questions</h2>
</div>

<div class="well">
	<%= link_to faq_path(anchor: "1") do %>
		1. My task has a label of "Date Not Specified"
	<% end %>
	<%= link_to faq_path(anchor: "2") do %>
	<% end %>
</div>

<div class="well">
	<a name="1">
		<b>
			1. My task has a label of "Date Not Specified"
		</b>
		<i>
			You have selected "Due" but have not specified a date yet. Click on the task, select a date, and save.
		</i>
	</a>
	<a name="2">
		<b>
			1. My task has a label of "Date Not Specified"
		</b>
		<i>
			You have selected "Due" but have not specified a date yet. Click on the task, select a date, and save.
		</i>
	</a>
</div>

app/views/pages/settings.html.erb
<h1>Settings</h1>

<%= link_to "Edit User Account", edit_user_registration_path %>
<%= link_to "Delete User Account", cancel_user_registration_path, method: :delete %>