config/routes.rb
Rails.application.routes.draw do

  resources :notes
  resources :tasks

  resources :projects, shallow: true do
    resources :tasks do
      member do
        put :pause, :stop
      end
    end
    resources :steps do
      member do
        put :order_up
      end
    end
    resources :entities
  end

  get "newchecklist" => "projects#newchecklist"
  get "newprocess" => "projects#newprocess"

  devise_for :accounts
  
  resources :accounts, :only => [:index, :new, :create, :destroy]

  devise_for :users
  resources :users, only: [:index]
  root 'pages#home'
  get "about" => "pages#about"
  get "settings" => "pages#settings"
  get "dashboard" => "pages#dashboard"
  get "faq" => "pages#faq"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  	accepts_nested_attributes_for :tasks, :reject_if => :all_blank, :allow_destroy => true
  	has_many :steps
  	accepts_nested_attributes_for :steps, :reject_if => :all_blank, :allow_destroy => true
  	has_many :entities
  	accepts_nested_attributes_for :entities, :reject_if => :all_blank, :allow_destroy => true
  	
	belongs_to :account

	validates :title, presence: true

  default_scope { order('updated_at') }

  def to_param
    "#{id} #{title}".parameterize
  end

  #include PublicActivity::Model
  #tracked owner: Proc.new{ |controller, model| controller.current_user }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @users = User.where('account_num = ?',current_user.account_num)
    @projects = Project.where("creator IN (?)", @users.pluck(:email))
    @tasks = Task.where("project_id IN (?)", @projects.pluck(:id))
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @users = User.where('account_num = ?',current_user.account_num)
    @notes = Note.where("creator IN (?)", @users.pluck(:email))
    @projects = Project.where("creator IN (?)", @users.pluck(:email))
    @tasks = Task.where("project_id IN (?)", @projects.pluck(:id))
  end

  # GET /projects/new
  def new
    @users = User.where('account_num = ?',current_user.account_num)
    @projects = Project.where("creator IN (?)", @users.pluck(:email))
    @project = Project.new
  end

  # GET /projects/newchecklist
  def newchecklist
    @users = User.where('account_num = ?',current_user.account_num)
    @projects = Project.where("creator IN (?)", @users.pluck(:email))
    @project = Project.new
  end

  # GET /projects/newprocess
  def newprocess
    @users = User.where('account_num = ?',current_user.account_num)
    @projects = Project.where("creator IN (?)", @users.pluck(:email))
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @users = User.where('account_num = ?',current_user.account_num)
    @projects = Project.where("creator IN (?)", @users.pluck(:email))
  end

  # POST /projects
  # POST /projects.json
  def create
    @users = User.where('account_num = ?',current_user.account_num)
    @projects = Project.where("creator IN (?)", @users.pluck(:email))
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
        format.js
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @users = User.where('account_num = ?',current_user.account_num)
    @projects = Project.where("creator IN (?)", @users.pluck(:email))
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully deleted.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :category, :description, :creator, entities_attributes: [:id, :name, :notes, :contact, :step_id, :project_id, :created_at, :updated_at], tasks_attributes: [:id, :description, :done, :priority, :assignee, :started, :started_at, :paused_at, :completed_at, :creator, :created_at, :accepted, :completed_at, :_destroy])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_showentities.html.erb
<% @entity_count = 0 %>
<thead>
	<tr class="table-header">
		<th>#</th>
		<th>Entity</th>
		<th>Status</th>
		<th>Action(s)</th>
	</tr>
</thead>
<tbody>
	<% @project.entities.each do |entity| %>
		<% if entity.step_id == nil %>
			<tr>
		<% elsif entity.step_id == 0 %>
			<tr class="danger">
		<% elsif entity.step_id <= @project.steps.count %>
			<tr class="warning">
		<% else %>
			<tr class="success">
		<% end %>
			<td><%= @entity_count = @entity_count + 1 %></td>
			<td><%= link_to entity.name, edit_entity_path(entity)%></td>
			<td>
				<% if entity.step_id == nil || entity.step_id == 0 %>
					Unassigned
				<% elsif entity.step_id <= @project.steps.count %>
					on Step <%= entity.step_id %>
				<% else %>
					Complete
				<% end %>
			</td>
			<td>
				<div class="btn-group gray">
					<% if entity.step_id != nil %>
						<% if (entity.step_id > @project.steps.count) || entity.step_id == 0 %>
							<%= link_to raw("<i class=\"fa fa-bolt fa-fw\"></i>"), entity_path(entity, "entity[step_id]" => 1), :method => :put, :confirm => "Sure?", class: "btn btn-project btn-sm" %>
						<% end %>
					<% else %>
						<%= link_to raw("<i class=\"fa fa-bolt fa-fw\"></i>"), entity_path(entity, "entity[step_id]" => 1), :method => :put, :confirm => "Sure?", class: "btn btn-project btn-sm" %>
					<% end %>
					
					<%= link_to raw("<i class=\"fa fa-trash-o fa-fw\"></i>"), entity, method: :delete, data: { confirm: "Delete entity? This action cannot be undone" }, class: "btn btn-project btn-sm" %>
				</div>
			</td>
		</tr>
	<% end %>
</tbody>

app/views/projects/_showsteps.html.erb
<% @step_list_order = 0 %>
<thead>
	<tr class="table-header">
		<th>#</th>
		<th>Step Name</th>
		<th>Entities</th>
	</tr>
</thead>
<tbody>
	<% @project.steps.each do |step| %>
		<% @entity_count = 0 %>
		<% @step_list_order = @step_list_order + 1 %>
		<% step.order = @step_list_order %>

		<% @project.entities.each do |entity| %>
			<% if entity.step_id != nil && entity.step_id == step.order %>
				<% @entity_count = @entity_count + 1 %>
			<% end %>
		<% end %>
		<tr>
			<%= content_tag :td, :rowspan => @entity_count do %>
				<%= step.order %>
			<% end %>

			<%= content_tag :td, :rowspan => @entity_count do %>
				<%= link_to step.description, edit_step_path(step) %>
				<!--<span class="glyphicon glyphicon-chevron-right"></span>-->
				<% if @entity_count > 0 %>
					<!--<span class="badge"><%= @entity_count %></span>-->
				<% end %>

				<% if step.assignee != nil && step.assignee != "" %>
					<br><span class="label label-info">
						To
						<%= @users.where('email = ?',step.assignee).take.name %>
						<%#= f.select :assignee, User.where('id <> ?', current_user.id).pluck(:email), :prompt => "Select one" %>
					</span>
				<% end %>
			<% end %>

			<% if @entity_count == 0 %>
				<td>-</td></tr>
			<% end %>
			<%#= link_to raw("<i class=\"glyphicon glyphicon-arrow-up\"></i> Up"), step_path(step, "step[order]" => @step_list_order - 1), :method => :put, :confirm => "Sure?", class: "btn btn-default btn-sm" %>		 
			<% @entity_count = 0 %>
			<% @project.entities.each do |entity| %>
				<% if @entity_count > 0 %>
					<tr>
				<% end %>

				<% if entity.step_id == step.order %>
					<% if entity.step_id == 1 %>
						<% @entity_count = @entity_count + 1 %>
							<td class="well well-sm">
								<span 
								<% if entity.notes != "" || entity.contact != "" %>
									rel="tooltip" data-toggle="tooltip" data-placement="top" title="Notes: 
									<% if entity.notes != "" %>
										<%= entity.notes %>
									<% else %>
										None
									<% end %>
									&#013; Contact: 
									<% if entity.contact != "" %>
										<%= entity.contact %>
									<% else %>
										None
									<% end %>
									"
								<% end %>
									>
									<%= link_to entity.name, edit_entity_path(entity) %>
								</span>
								<div class="btn-group gray">
									<%= link_to raw("<i class=\"fa fa-ban fa-fw\"></i>"), entity_path(entity, "entity[step_id]" => 0), :method => :put, :confirm => "Sure?", class: "btn btn-project btn-sm" %>
									<%= link_to raw("<i class=\"fa fa-check fa-fw\"></i>"), entity_path(entity, "entity[step_id]" => step.order + 1), :method => :put, :confirm => "Sure?", class: "btn btn-project btn-sm" %>
								</div>
							</td>
						</tr>
					<% else %>
						<% @entity_count = @entity_count + 1 %>
							<td class="well well-sm">
								<span 
								<% if entity.notes != "" || entity.contact != "" %>
									rel="tooltip" data-toggle="tooltip" data-placement="top" title="Notes: 
									<% if entity.notes != "" %>
										<%= entity.notes %>
									<% else %>
										None
									<% end %>
									&#013; Contact: 
									<% if entity.contact != "" %>
										<%= entity.contact %>
									<% else %>
										None
									<% end %>
									"
								<% end %>
									>
									<%= link_to entity.name, edit_entity_path(entity) %>
								</span>
								<div class="btn-group gray">
									<%= link_to raw("<i class=\"fa fa-chevron-left fa-fw\"></i>"), entity_path(entity, "entity[step_id]" => step.order - 1), :method => :put, :confirm => "Sure?", class: "btn btn-project btn-sm" %>
									<%= link_to raw("<i class=\"fa fa-check fa-fw\"></i>"), entity_path(entity, "entity[step_id]" => step.order + 1), :method => :put, :confirm => "Sure?", class: "btn btn-project btn-sm" %>
								</div>
							</td>
						</tr>
					<% end %>
				<% end %>
			<% end %>
			<!--<% if @entity_count == 0 %>
				<td>None Assigned</td>
			<% elsif @entity_count > 0 %>
				<td><span class="badge"><%= @entity_count %></span></td>
			<% end %>-->
		<tr>
	<% end %>
</tbody>
<tr>
	<td colspan="3">
		<% @total_entity_count = Entity.where('project_id = ?', @project.id).count %>
		
		<% @active_entity_count = Entity.where('project_id = ?', @project.id).where('step_id <= ?', @project.steps.count).where('step_id > ?', 0).count %>

		<% @complete_entity_count = Entity.where('project_id = ?', @project.id).where('step_id = ?', @project.steps.count+1).count %>

		<% @inactive_entity_count = @total_entity_count - (@active_entity_count + @complete_entity_count) %>
		
		<% if @active_entity_count == 0 || @total_entity_count == 0 %>
			<% @active_entity_pc_number = 0 %>
			<% @active_entity_pc = 0 %>
		<% else %>
			<% @active_entity_pc_number = @active_entity_count.to_f / @total_entity_count * 100 %>
			<% @active_entity_pc = number_to_human(@active_entity_pc_number) %>
		<% end %>

		<% if @complete_entity_count == 0 || @total_entity_count == 0 %>
			<% @complete_entity_pc_number = 0 %>
			<% @complete_entity_pc = 0 %>
		<% else %>			
			<% @complete_entity_pc_number = @complete_entity_count.to_f / @total_entity_count * 100 %>
			<% @complete_entity_pc = number_to_human(@complete_entity_pc_number) %>
		<% end %>

		<% if @inactive_entity_count == 0 || @total_entity_count == 0 %>
			<% @inactive_entity_pc = 0 %>
		<% else %>			
			<% @inactive_entity_pc = 100 - (@active_entity_pc_number + @complete_entity_pc_number) %>
		<% end %>

		<div class="progress">		  
		  <div class="progress-bar progress-bar-danger" style="width: <%= @inactive_entity_pc %>%">
		    <%= @inactive_entity_count %> to open
		  </div>
		  <div class="progress-bar progress-bar-warning" style="width: <%= @active_entity_pc %>%">
		    <%= @active_entity_count %> to go
		  </div>
		  <div class="progress-bar progress-bar-success" style="width: <%= @complete_entity_pc %>%">
		    <%= @complete_entity_count %> done
		  </div>
		</div>

	</td>
	<!--
	-->
</tr>
<tr>
	<td>
		<span class="label label-danger">Closed</span>
		<span class="label label-warning">In Progress</span>
		<span class="label label-success">Complete</span>
	</td>
</tr>
<!--
<tr class="success">
	<td></td>
	<td>Completed</td>
	<% @project.entities.each do |entity| %>
		<% if entity.step_id != nil %>
			<% if entity.step_id > @project.steps.count %>
				<td class="well well-sm">
					<%= link_to entity.name, edit_entity_path(entity) %>
					<%= link_to raw("<i class=\"glyphicon glyphicon-pushpin\"></i> Reopen"), entity_path(entity, "entity[step_id]" => 1), :method => :put, :confirm => "Sure?", class: "btn btn-default btn-sm" %>
					<%#= link_to raw("<i class=\"glyphicon glyphicon-ok\"></i> Done"), entity_path(entity, "entity[step_id]" => step.order + 1), :method => :put, :confirm => "Sure?", class: "btn btn-default btn-sm" %>
				</td>
			<% end %>
		<% end %>
	<% end %>
</tr>
-->

app/views/projects/edit_task.html.erb
<h1>Adding new task</h1>

<%= render 'form_task' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% if @projects.count > 0 %>
  <div class="row">
    <% @projects.sort_by{|e| e[:title]}.each do |project| %>
      <div class="col-md-3">
        <div class="panel panel-info">
          <div class="panel-heading">
            <% if project.category=="checklist" %>
              <i class="fa fa-check-circle-o fa-lg pull-right fa-panel" style="color:#fff"></i>
            <% elsif project.category=="process" %>
              <i class="fa fa-list-ol fa-lg pull-right fa-panel" style="color:#fff"></i>
            <% end %>
            <%= link_to truncate(project.title, length: 25, omission: '...'), project %>
          </div>
          <table class="table table-condensed">
            <tr>
              <td align="center">
                <% if project.category == "checklist" %>
                <% @project_open_task_count = project.tasks.where('done = ?', false).count %>
                  <% if @project_open_task_count > 0 %>
                    <input type="text" 
                      value="<%= @project_open_task_count %>" data-max="<%= project.tasks.count %>" 
                      class="dial1" data-width="100" data-height="85" data-angleArc="250" data-angleOffset="-125" data-readOnly=true data-fgColor="#f0ad4e" data-bgColor="#5cb85c" data-thickness=".2" data-fontWeight="100" data-font="Helvetica">
                    <script>
                    $(function() {
                        $(".dial1").knob({
                        }).addClass('animated zoomIn');
                    });
                    </script>
                  <% else %>
                    <input type="text" 
                      value="<%= project.tasks.where('done = ?', true).count %>" data-max="<%= project.tasks.where('done = ?', true).count %>" 
                      class="dial2" data-width="100" data-height="85" data-angleArc="250" data-angleOffset="-125" data-readOnly=true data-fgColor="#5cb85c" data-bgColor="#5cb85c" data-thickness=".2" data-fontWeight="100" data-font="Helvetica">
                    <script>
                    $(function() {
                        $(".dial2").knob({
                        }).addClass('animated zoomIn'); 
                    });
                    </script>
                  <% end %>
                <% elsif project.category == "process" %>
                  <% if project.entities.where('step_id > ?', 0).where('step_id <= ?',project.steps.count).count > 0 %>
                    <input type="text" 
                      value="<%= project.entities.where('step_id > ?', 0).where('step_id <= ?',project.steps.count).count %>"
                      data-max="<%= project.entities.where('step_id > ?', 0).count %>"
                      class="dial3" data-width="100" data-height="85" data-angleArc="250" data-angleOffset="-125" data-readOnly=true data-fgColor="#f0ad4e" data-bgColor="#5cb85c" data-thickness=".2" data-fontWeight="100" data-font="Helvetica">
                    <script>
                    $(function() {
                        $(".dial3").knob({
                        }).addClass('animated zoomIn'); 
                    });
                    </script>
                  <% else %>
                    <input type="text" 
                      value="0" 
                      class="dial4" data-width="100" data-height="85" data-angleArc="250" data-angleOffset="-125" data-readOnly=true data-fgColor="#5cb85c" data-bgColor="#5cb85c" data-thickness=".2" data-fontWeight="100" data-font="Helvetica">
                    <script>
                    $(function() {
                        $(".dial4").knob({
                          'min': 0,
                          'max': 1,
                          'fontWeight': 900
                        }).addClass('animated zoomIn'); 
                    });
                    </script>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td align="center">
                <% if project.description != "" %>
                  <%= truncate(project.description, length: 30, omission: '...') %>
                <% else %>
                  <i>No Description</i>
                <% end %>
              </td>
            </tr>
            <tr class="gray">
              <td align="center">
                <div class="btn-group">
                  <%= link_to project, class: "btn btn-default btn-sm btn-project", title: 'View', rel: 'tooltip' do %>
                    <i class="fa fa-eye fa-lg"></i>
                  <% end %>
                  <% if project.category == "checklist" %>
                    <%= link_to new_project_task_path(project), class: "btn btn-default btn-sm btn-project", title: 'Add Task', rel: 'tooltip' do%>
                     <i class="fa fa-plus fa-lg"></i>
                    <% end %>
                   <% elsif project.category == "process" %>
                    <%= link_to new_project_entity_path(project), class: "btn btn-default btn-sm btn-project", title: 'Add Entity', rel: 'tooltip' do%>
                     <i class="fa fa-plus fa-lg"></i>
                    <% end %>
                  <% end %>
                  <% if project.creator == current_user.email %>
                    <%= link_to edit_project_path(project), class: "btn btn-default btn-sm btn-project", title: 'Edit', rel: 'tooltip' do %>
                      <i class="fa fa-pencil fa-lg"></i>
                     <% end %>
                    <%= link_to project, method: :delete, data: { confirm: 'Delete project? This action cannot be undone' }, class: "btn btn-default btn-sm btn-project", title: 'Delete', rel: 'tooltip' do %>
                        <i class="fa fa-trash-o fa-lg"></i>
                    <% end %>
                  </div>
                <% end %>
              </td>
            </tr>
          </table>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h1 class="center-align">Create your first Project<h1>
  <br>
  <div class="container-fluid">
    <div class="col-md-6 center-align">
      <%= link_to newchecklist_path, class: "project-button", :method => :get do %>
        <span class="feature-icon">
            <span class="fa-stack fa-2x">
              <i class="fa fa-circle fa-stack-2x blue"></i>
              <i class="fa fa-check-circle-o fa-stack-1x fa-inverse"></i>
            </span>
        </span>
        <span class="project-text">
          <span class="blue">
            New Checklist
          </span>
        </span>
      <% end %>
      <div class="project-content">
        A to do list with items that are either <i>pending</i> or <i>completed</i>.
        <br><br>  
        Some examples would be your task list for the day, a grocery list, or anything where you would check off each item as done.
      </div>
    </div>

    <div class="col-md-6 center-align">
      <%= link_to newprocess_path, class: "project-button", :method => :get do %>
        <span class="feature-icon">
            <span class="fa-stack fa-2x">
              <i class="fa fa-circle fa-stack-2x orange"></i>
              <i class="fa fa-list-ol fa-stack-1x fa-inverse"></i>
            </span>
        </span>
        <span class="project-text">
          <span class="orange">
            New Process
          </span>
        </span>
      <% end %>
      <div class="project-content">
        A pipeline with multiple steps and different entities <i>(e.g. candidates, clients, etc.)</i>
        <br><br>  
        Some examples would be your sales pipeline, hiring process, or any other repeatable list of things you need to do.
      </div>
    </div>
  </div>
<% end %>

app/views/projects/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'All Projects', projects_path %></li>
  <li class="active">New Project</li>
</ol>

<div class="well">
	<%= render 'form' %>
</div>

<ul class="pager">
	<li class="previous"><%= link_to 'Back', projects_path %></li>
</ul>

app/views/projects/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'All Projects', projects_path %></li>
  <li class="active"><%= @project.title %></li>
</ol>

<div class="panel panel-info">
	<div class="panel-heading container-fluid">
    <% if @project.category == "checklist" %>
      <i class="fa fa-check-circle-o fa-lg"></i>
    <% elsif @project.category == "process" %>
      <i class="fa fa-list-ol fa-lg"></i>
    <% end %>

    <strong><%= @project.title %></strong>

    <% if @project.category == "checklist" %>
      <span class="badge badge-light">
        <%= @project.tasks.count %>
      </span>
    <% elsif @project.category == "process" %>
      <span class="badge badge-light">
        <%= @project.steps.count %>
      </span>
    <% end %>

    <% if @project.creator == current_user.email %>
      <div class="btn-group">
        <%= link_to edit_project_path(@project), class: "btn btn-default btn-sm" do %>
          <i class="fa fa-pencil fa-lg"></i>
         <% end %>
        <%= link_to @project, method: :delete, data: { confirm: 'Delete project? This action cannot be undone' }, class: "btn btn-default btn-sm" do %>
          <i class="fa fa-trash-o fa-lg"></i>
        <% end %>
      </div>
    <% end %>
      
      <% if @project.category == "checklist" %>
        <%= link_to new_project_task_path(@project), class: "btn btn-default btn-sm" do%>
         <i class="fa fa-plus fa-lg"></i>
         Add Task
        <% end %>

        <button class="btn btn-legend btn-sm pull-right" data-toggle="modal" data-target=".bs-example-modal-sm">
          <i class="fa fa-question-circle fa-lg"></i>
        </button>
        
        <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Key</h4>
              </div>
              <div class="modal-body">
                <div class="legend">
                  <i class="fa fa-play fa-fw"></i> Start/Resume<br>
                  <i class="fa fa-pause fa-fw"></i> Pause<br>
                  <i class="fa fa-stop fa-fw"></i> Stop<br>
                  <i class="fa fa-refresh fa-fw"></i> Reset<br>
                  <i class="fa fa-check fa-fw"></i> Complete<br>
                  <i class="fa fa-bolt fa-fw"></i> Reopen<br>
                  <i class="fa fa-trash-o fa-fw"></i> Delete
                </div>
              </div>
            </div>
          </div>
        </div>
     <% elsif @project.category == "process" %>
      <%= link_to new_project_step_path(@project), class: "btn btn-default btn-sm" do%>
       <i class="fa fa-plus fa-lg"></i>
       Add Step
      <% end %>
      <button class="btn btn-legend btn-sm pull-right" data-toggle="modal" data-target=".bs-example-modal-sm">
        <i class="fa fa-question-circle fa-lg"></i>
      </button>
      <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title">Key</h4>
            </div>
            <div class="modal-body">
              <div class="legend">
                <i class="fa fa-ban fa-fw"></i> Close<br>
                <i class="fa fa-chevron-left fa-fw"></i> Back<br>
                <i class="fa fa-check fa-fw"></i> Done<br>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
	</div>

  <% if @project.description != nil && @project.description != "" %>
  	<div class="panel-body">
  		Description: <%= @project.description %>
  	</div>
  <% end %>
    
  <table class="table table-hover">
    <% if @project.category == "process" %>
        <%= render 'showsteps' %>
    <% end %>
    <% if @project.category == "checklist" %>
      <%= render 'showtasks' %>
    <% end %>
  </table>

  <div class="panel-footer">
    <% if @project.category == "checklist" %>
      <%= link_to new_project_task_path(@project), class: "btn btn-default btn-sm" do%>
       <i class="fa fa-plus fa-lg"></i>
       Add Task
      <% end %>
     <% elsif @project.category == "process" %>
      <%= link_to new_project_step_path(@project), class: "btn btn-default btn-sm" do%>
       <i class="fa fa-plus fa-lg"></i>
       Add Step
      <% end %>
    <% end %>
  </div>
</div>

<% if @project.category == "process" %>
  <div class="panel panel-info">
    <div class="panel-heading">
      <strong>Entities</strong>
      <span class="badge badge-light">
        <%= @project.entities.count %>
      </span>
      <%= link_to new_project_entity_path(@project), class: "btn btn-default btn-sm" do%>
         <i class="fa fa-plus fa-lg"></i>
         Add Entity
      <% end %>
      <button class="btn btn-legend btn-sm pull-right" data-toggle="modal" data-target=".bs-example-modal-sm1">
        <i class="fa fa-question-circle fa-lg"></i>
      </button>
      <div class="modal fade bs-example-modal-sm1" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <h4 class="modal-title">Key</h4>
            </div>
            <div class="modal-body">
              <div class="legend">
                <i class="fa fa-bolt fa-fw"></i> Open/Reopen<br>
                <i class="fa fa-trash-o fa-fw"></i> Delete<br>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
    <table class="table table-hover">
      <%= render 'showentities' %>
    </table>
    <div class="panel-footer">
      <%= link_to new_project_entity_path(@project), class: "btn btn-default btn-sm" do%>
         <i class="fa fa-plus fa-lg"></i>
         Add Entity
        <% end %>    
    </div>
  </div>
<% end %>


<ul class="pager">
	<li class="previous"><%= link_to 'Back', projects_path %></li>
</ul>