config/routes.rb
Rails.application.routes.draw do

  resources :notes
  resources :tasks

  resources :projects, shallow: true do
    resources :tasks do
      member do
        put :pause, :stop
      end
    end
    resources :steps do
      member do
        put :order_up
      end
    end
    resources :entities
  end

  get "newchecklist" => "projects#newchecklist"
  get "newprocess" => "projects#newprocess"

  devise_for :accounts
  
  resources :accounts, :only => [:index, :new, :create, :destroy]

  devise_for :users
  resources :users, only: [:index]
  root 'pages#home'
  get "about" => "pages#about"
  get "settings" => "pages#settings"
  get "dashboard" => "pages#dashboard"
  get "faq" => "pages#faq"

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-custom" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <% if user_signed_in? %>
          <%= link_to root_path do %>
              <% image_tag(image_path("catalist-white-new-large.png"), size: "140x30", class: "logo") %>
          <% end %>
        <% elsif account_signed_in? %>
          <%= link_to edit_account_registration_path do %>
            <% image_tag(image_path("catalist-white-new-large.png"), size: "140x30", class: "logo") %>
          <% end %>
        <% else %>
            <%= link_to do %>
              <% image_tag(image_path("catalist-white-new-large.png"), size: "140x30", class: "logo") %>
            <% end %>
        <% end %>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if account_signed_in? %>
          <li><%= link_to edit_account_registration_path, class: "btn-default" do %>
            <i class="fa fa-cog fa-lg header"></i>
            Settings
            <% end %>
          </li>
       <% end %>
       
       <% if user_signed_in? || account_signed_in? %>
          <% if (account_signed_in? && user_signed_in?) || account_signed_in? %>
           <li class="<%= 'active' if current_page?(accounts_path) %>"><%= link_to accounts_path, class: "btn-default" do %>
              <!--<i class="fa fa-users fa-lg header"></i>-->
              Users
              <% end %>
            </li>
          <% else %>
            <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to users_path, class: "btn-default" do %>
              <!--<i class="fa fa-users fa-lg header"></i>-->
              Team
              <% end %>
            </li>
          <% end %> 

        <% end %>

        <% if user_signed_in? %>
          <%# @awaiting = [] %>
          <%# @projects.each do |project| %>
            <%# @awaiting = @awaiting + project.tasks.where('creator != ?', current_user.email).where('assignee = ?', current_user.email).where('done = ?', false).where('accepted = ?', nil) %>
          <%# end %>
          <li class="<%= 'active' if current_page?(projects_path) %>"><%= link_to projects_path, class: "btn-default" do %>
            <!--<i class="fa fa-folder-open fa-lg header"></i>-->
            Projects
            <% end %>
          </li>
          <% if @projects %>
            <% if @projects.count > 0 %>
              <li class="<%= 'active' if current_page?(tasks_path) %>">
                <%= link_to tasks_path, class: "btn-default" do %>
                  <!--<i class="fa fa-folder-open fa-lg header"></i>-->
                  Tasks 
                  <%# if @awaiting.count > 0 %>
                    <%#= @awaiting.count %>
                  <%# end %>
                <% end %>
              </li>
            <% end %>
          <% end %>
          <li class="<%= 'active' if current_page?(notes_path) %>"><%= link_to notes_path, class: "btn-default" do %>
            <!--<i class="fa fa-comments fa-lg header"></i>-->
            Notes
            <% end %>
          </li>
          <% if current_page?(projects_path) %>
            <% if @projects %>
              <% if @projects.count > 0 %>
                <li>
                  <%= button_to newchecklist_path, class: "btn btn-default navbar-btn checklist btn-sm", :method => :get do %>
                    New Checklist
                    <i class="fa fa-check-circle-o fa-lg"></i>
                  <% end %>
                </li>
                <li>
                  <%= button_to newprocess_path, class: "btn btn-default navbar-btn process btn-sm", :method => :get do %>
                    New Process
                    <i class="fa fa-list-ol fa-lg"></i>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          <% end %>
          <% if current_page?(notes_path)%>
            <% if @notes %>
              <% if @notes.count > 0 %>
                <li>
                  <%= button_to new_note_path, class: "btn btn-default navbar-btn btn-sm", :method => :get do %>
                    New Note
                    <i class="fa fa-plus fa-lg"></i>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          <% end %>
          <!--
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" class="btn-default" do>
              <i class="fa fa-plus fa-lg header"></i>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to new_project_path do %>
                  Project
                <% end %>
              </li>
              <li>
                <%= link_to new_note_path do %>
                  Note
                <% end %>
              </li>
            </ul>
          </li>
        -->
        </ul>
        <!--
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        -->
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" class="btn btn-default" data-toggle="dropdown">
              <i class="fa fa-envelope fa-lg header"></i>
              <!--Contact
              <b class="caret"></b>-->
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= mail_to "support@catalist.me", subject: "[BUG REPORT]", body: "Sorry for the inconvenience. We will get back to you as soon as possible!\n\nPlease provide as many details as you can including the steps that caused the error\n\n*Bug Details*\n\nUser: #{current_user.email}\nTime: #{Time.now}\n-------\nUser Comments:\n", class: "btn-default" do %>
                  Report Bug
                <% end %>
              </li>
              <li>
                <%= mail_to "support@catalist.me", subject: "[GENERAL REQUEST]", body: "Let us know how we can be of assistance!\n\nNeed additional users? Forgot password? Need suggestions? No problem!\n\n*Request Details*\n\nUser: #{current_user.email}\nTime: #{Time.now}\n-------\nUser Comments:\n", class: "btn-default" do %>
                  General Request
                <% end %>
              </li>
            </ul>
          </li>
          
          <li class="<%= 'active' if current_page?(about_path) %>">
            <%= link_to about_path do %>
              <i class="fa fa-info fa-lg header"></i>
            <% end %>
          </li>
          <!--
          <li class="<%#= 'active' if current_page?(faq_path) %>">
            <%#= link_to faq_path do %>
              <i class="fa fa-question fa-lg header"></i>
            <%# end %>
          </li>
        -->

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" class="btn btn-default" data-toggle="dropdown">
              <i class="fa fa-user fa-lg header"></i>
              <!--<%= current_user.name %>
              <b class="caret"></b>-->
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <% if current_user.supervisor %>
                <li><%= link_to "Dashboard", dashboard_path %></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <div><%#= Time.now.in_time_zone("Central Time (US & Canada)").to_s.split(" ").second %></div>
        <% end %>
      </ul>

      <% if account_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" class="btn btn-default" data-toggle="dropdown">
                <i class="fa fa-lock fa-lg header"></i>
                <%= current_account.email %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Log Out", destroy_account_session_path, method: :delete %></li>
              </ul>
            </li>
          <div><%#= Time.now.in_time_zone("Central Time (US & Canada)").to_s.split(" ").second %></div>
        </ul>
      <% end %>

      <% if !(user_signed_in? || account_signed_in?) %>
        <ul class="nav navbar-nav navbar-right">
          <p class="navbar-text">
            Already have an invite?
          </p>
          <li class="navbar-link signin">
            <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
          </li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Catalist" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- For the Font Awesome ability -->
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/jquery.datetimepicker.css"/ >
    <!-- For Chart.js -->
    <script src="Chart.js"></script>
    <!-- For Morris.js -->
    <!--
    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.5.1.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.5.1.min.js"></script>
    -->
    <!-- For Feedback Daddy, Who's your daddy?!? 
    <script type='text/javascript'>
    var pq_bid = '4447e30a9068ba59e5622cd14f1cb6a0';
    var pq_elm_id = 'popup_question';
    </script>
    <script type='text/javascript' src='https://s.feedbackdaddy.com/qs.js'></script>
    -->
    <!-- For Animate.css -->
    <link rel="stylesheet" href="animate.min.css">
    <!-- For Bootstrap Tooltips -->
    <script type="text/javascript">
        $(function () {
            $("[rel='tooltip']").tooltip();
        });
    </script>
    
  </head>
  <body>

    <%= render 'layouts/header' %>
    
    <div class="<%= 'container' if !(current_page?(root_path)) %>">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class:"alert alert-info animated fadeInDown") %>
      <% end %>
      <%= yield %>
    </div>

    <footer>
    </footer>
    <!-- For Olark -->
    <!-- begin olark code -->
    <script data-cfasync="false" type='text/javascript'>/*<![CDATA[*/window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){
    f[z]=function(){
    (a.s=a.s||[]).push(arguments)};var a=f[z]._={
    },q=c.methods.length;while(q--){(function(n){f[z][n]=function(){
    f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={
    0:+new Date};a.P=function(u){
    a.p[u]=new Date-a.p[0]};function s(){
    a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){
    hd="head";return["<",hd,"></",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"></",i,">"].join("")}var i="body",m=d[i];if(!m){
    return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){
    b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{
    b.contentWindow[g].open()}catch(w){
    c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{
    var t=b.contentWindow[g];t.write(p());t.close()}catch(x){
    b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({
    loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
    /* custom configuration goes here (www.olark.com/documentation) */
    olark.identify('5071-727-10-9778');/*]]>*/</script><noscript><a href="https://www.olark.com/site/5071-727-10-9778/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a></noscript>
    <!-- end olark code -->
  </body>
</html>